spring:
  application:
    name: notification-service
  autoconfigure:
    exclude:
      - co.kremnev.starter.KafkaNotificationProducerAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: co.kremnev.starter
    listener:
      ack-mode: manual
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bankdb?currentSchema=notifications}
    username: ${DB_USERNAME:bankuser}
    password: ${DB_PASSWORD:bankpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notifications
