spring:
  application:
    name: notification-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        root: /services
      config:
        root: /config
  config:
    import: "optional:zookeeper:"

server:
  port: 8085
