apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.fullnameOverride }}
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
