spring:
  application:
    name: my-bank-front-app

server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      gateway:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
