spring:
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/certs}
      client:
        registration:
          transfer-service-client:
            client-id: ${OAUTH2_CLIENT_ID:transfer-service-client}
            client-secret: ${OAUTH2_CLIENT_SECRET:transfer-secret}
            authorization-grant-type: client_credentials
            scope: accounts,notifications
        provider:
          transfer-service-client:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/token}

my-bank:
  security:
    scope: transfer
  oauth2-client:
    registration-id: transfer-service-client

server:
  port: 8084

resilience4j:
  circuitbreaker:
    instances:
      transfer-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
