spring:
  application:
    name: transfer-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        root: /services
      config:
        root: /config
  config:
    import: "optional:zookeeper:"

server:
  port: 8084

resilience4j:
  circuitbreaker:
    instances:
      transfer-service:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
