{{- range $name, $svc := .Values }}
{{- if and (kindIs "map" $svc) (hasKey $svc "secrets") $svc.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
stringData:
  {{- range $key, $val := $svc.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
