spring:
  application:
    name: accounts-service
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        root: /services
      config:
        root: /config
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/my-bank
  config:
    import: "optional:zookeeper:"
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb?currentSchema=accounts
    username: bankuser
    password: bankpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: accounts

server:
  port: 8082
