spring:
  application:
    name: accounts-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/certs}
      client:
        registration:
          accounts-service-client:
            client-id: ${OAUTH2_CLIENT_ID:accounts-service-client}
            client-secret: ${OAUTH2_CLIENT_SECRET:accounts-secret}
            authorization-grant-type: client_credentials
            scope: notifications
        provider:
          accounts-service-client:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/my-bank/protocol/openid-connect/token}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bankdb?currentSchema=accounts}
    username: ${DB_USERNAME:bankuser}
    password: ${DB_PASSWORD:bankpass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: accounts

my-bank:
  security:
    scope: accounts
  oauth2-client:
    registration-id: accounts-service-client

server:
  port: 8082
